services:
  - type: web
    name: html-to-image-api
    env: python
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x ./bin/wkhtmltoimage && python server.py
    autoDeploy: true
    plan: free
